### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by Caberhagen** [stfc2/Scheduler#6]
Hi @ all

today i startet a new clean install from master branch.
Now i have php error message in the server log:

PHP Notice:  Undefined variable: sdl in //scheduler/moves_main.php on line 24
PHP Fatal error:  Call to a member function log() on null in /scheduler/moves_main.php on line 24

System is a new deb 8 with php 5.5

make a test on deb 7 and the same in the log.

**Comment by kirirur** [comment]
Hello, you need to launch moves_start.php instead of moves_main.php, that creates the required environment.

**Comment by Caberhagen** [comment]
Hi

So simple. To long ago since last install...
Thnx
Am 21.08.2015 20:52 schrieb "Andrea Carolfi" <notifications@github.com>:
