### ISSUE TITLE
double script_path for combat module

### ISSUE THREAD

**Issue by Caberhagen** [stfc2/Scheduler#7]
Hi

in file moves_common we define the path to bin/moves_combat.
After the first use uf combat i have a php error. because we have defined the script path in config.inc.php and in moves_combat.php. But the config.inc.php is includet to moves_common.php.
I have set in config.inc.php the script path to the location of bin/moves_combat.
Set i moves_common.php script path to ' ' and it works fine.

we remove the Line in moves_common?

**Comment by Caberhagen** [comment]
Looks as i have it false now.
Witch path i have to set in config.inc.php in scheduler??

I know in moves commen its the path to moves-combat.

Fight works atm. But colonisation and spio not.

**Comment by Caberhagen** [comment]
Ok problem found now.
i have reverted to scheduler 1.1.6 and all works fine.

**Comment by kirirur** [comment]
OK, but is there a regression in latest version or not?

**Comment by Caberhagen** [comment]
I see in the log, it stuck in moves_action24.
Can be a problem from the not finished enhancement from Kail.

**Comment by Caberhagen** [comment]
I think the print to log was:

undefined variable offset on line 592

**Comment by kirirur** [comment]
Hello,

please, could you make a new test again? Because line 592 of moves_action_24.php is part of a mySQL query:

                    building_5 = 0,

Besides, I'm sorry but I don't understand the double path definition.

moves_common.php define:

```php
define('MV_COMBAT_BIN_PATH', $script_path . 'stfc-moves-combat/bin/moves_combat');
```

and file config.script.php define:

```php
// This should point to the directory where the daemons game are installed.
$script_path = '/home/stfc/daemons/';
```

**Comment by Caberhagen** [comment]
No problem. The double path was from combat not working. and i searched to deep around.
Yes i make a test. But i need some time.

**Comment by kirirur** [comment]
Sure, no problem!

**Comment by Caberhagen** [comment]
Sorry for the question, but i have some fault with fly actions.
The paht in config from scheduler to daemons have to point to: scheduler folder. I am right or not???

**Comment by kirirur** [comment]
Hello,

It really depends on your installation.

Suppose you have folder /home/stfc.

You can put inside the scheduler and the combat demon. Let call this folder scheduler and combat.

You will have:

/home/stfc/scheduler
/home/stfc/combat

If so, you will have to set:
```php
$script_path = '/home/stfc/';
```
In file config.script.php and define:
```php
define ('MV_COMBAT_BIN_PATH', $script_path . 'combat/bin/moves_combat');
```

**Comment by Caberhagen** [comment]
Thnx.

I try it. Because i don't want the schedluer in the web folder.
Because it can called from web.

so i have the game in: 
/var/www/virtual/stfc2.ch/htdocs/game

and the scheduler in:
/var/www/virtual/stfc2.ch/cgi-bin/scheduler

and combat in:
/var/www/virtual/stfc2.ch/cgi-bin/combat

I try now:
scrip_path: /var/www/virtual/cgi-bin/
and in moves-common:
combat/moves_combat

15min i know more.

**Comment by Caberhagen** [comment]
from your post, /home/stfc is the base folder from game?

**Comment by Caberhagen** [comment]
today is no my day.

i don't understand it.

Fighting, colonisation and analysing a plant works.
on a living plant the spio function want work.

i don' see that ever.

**Comment by Caberhagen** [comment]
Hi @ all

so tried a lot of experiments with the path. That is not the problem.

Just one point not working. all other seems well.

My Problem:

With a Scout the actions:  Station, Planet analysis, Attack, works well.

But Spy, the ship fly to the plante, takes another 3 minute on planet, then the ship is back at starting planet without a message on logbook or any error everywehre in the system.

Any hints for that?

**Comment by Kail72** [comment]
Spy module is not working and not supported anymore, we should get rid of
it :)

2015-09-05 10:20 GMT+02:00 Caberhagen <notifications@github.com>:

**Comment by Caberhagen** [comment]
Ohh thanks. 
Good to know.
So we have to remove the command.

i close because all from spy not working.
